version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: fleet_postgres
    environment:
      POSTGRES_DB: fleetdb
      POSTGRES_USER: fleet
      POSTGRES_PASSWORD: fleetpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
